# this yaml snippet is stored as openapi/openapi.yaml
openapi: 3.0.0
info:
  title: Root finder
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
paths:
  /api/newtonraphson:
    post:
      description: Perform root finding with the Newton Raphson algorithm
      operationId: api.calculate
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NRRequest'
            example:
              epsilon: 0.001
              guess: -20
      responses:
        '200':
          description: The found root
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NRResponse'
components:
  schemas:
    NRRequest:
      {
        "type": "object",
        "description": "this JSON document is later referred to as <<request-schema>>",
        "properties": {
          "epsilon": {
            "title": "Epsilon",
            "type": "number",
            "minimum": 0
          },
          "guess": {
            "title": "Initial guess",
            "type": "number"
          }
        },
        "required": [
          "epsilon",
          "guess"
        ],
        "additionalProperties": false
      }
    NRResponse:
      {
        "type": "object",
        "description": "this JSON document is later referred to as <<response-schema>>",
        "properties": {
            "root": {
              "title": "Root",
              "type": "number"
            }
        },
        "required": [
            "root"
        ],
        "additionalProperties": false
      }